//
//  SoraFunction.h
//  Hoshizora
//
//  Created by Robert Bu on 8/15/11.

//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
#ifndef SoraFunction_h
#define SoraFunction_h

#include "detail/SoraFunction0.h"
#include "detail/SoraFunction1.h"
#include "detail/SoraFunction2.h"
#include "detail/SoraFunction3.h"
#include "detail/SoraFunction4.h"
#include "detail/SoraFunction5.h"
#include "detail/SoraFunction6.h"
#include "detail/SoraFunction7.h"
#include "detail/SoraFunction8.h"
#include "detail/SoraFunction9.h"
#include "detail/SoraFunction10.h"
#include "detail/SoraFunction11.h"
#include "detail/SoraFunction12.h"

namespace sora {
    
    template<typename SIG, typename T>
    static SoraFunction<SIG> MakeFunction(const T& t) {
        return SoraFunction<SIG>(t);
    }
    
} // namespace sora

#endif
