// This is C2E2f_passthru from "The Cg Tutorial" (Addison-Wesley, ISBN
// 0321194969) by Randima Fernando and Mark J. Kilgard.  See page 53.

struct C2E2f_Output {
  float4 color : COLOR;
};

C2E2f_Output C2E2f_passthru(float2 texCoord : TEXCOORD0,
                            uniform sampler2D tex: TEX0)
{
  C2E2f_Output OUT;
  OUT.color = tex2D(tex, texCoord);
  float col = (OUT.color.r + OUT.color.g + OUT.color.b) / 3.0;
  OUT.color.r = col;
  OUT.color.g = col;
  OUT.color.b = col;
  return OUT;
}
