//
//  SoraFunctionInclude.h
//  Hoshizora
//
//  Created by Robert Bu on 8/16/11.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
#if SORA_FUNCTION_NUM_ARGS == 0
    #ifndef SORA_FUNCTION_0
        #define SORA_FUNCTION_0
        #include "SoraFunctionTemplate.h"
    #endif
#elif SORA_FUNCTION_NUM_ARGS == 1
    #ifndef SORA_FUNCTION_1
        #define SORA_FUNCTION_1
        #include "SoraFunctionTemplate.h"
    #endif
#elif SORA_FUNCTION_NUM_ARGS == 2
    #ifndef SORA_FUNCTION_2
        #define SORA_FUNCTION_2
        #include "SoraFunctionTemplate.h"
    #endif
#elif SORA_FUNCTION_NUM_ARGS == 3
    #ifndef SORA_FUNCTION_3
        #define SORA_FUNCTION_3
        #include "SoraFunctionTemplate.h"
    #endif
#elif SORA_FUNCTION_NUM_ARGS == 4
    #ifndef SORA_FUNCTION_4
        #define SORA_FUNCTION_4
        #include "SoraFunctionTemplate.h"
    #endif
#elif SORA_FUNCTION_NUM_ARGS == 5
    #ifndef SORA_FUNCTION_5
        #define SORA_FUNCTION_5
        #include "SoraFunctionTemplate.h"
    #endif
#elif SORA_FUNCTION_NUM_ARGS == 6
    #ifndef SORA_FUNCTION_6
        #define SORA_FUNCTION_6
        #include "SoraFunctionTemplate.h"
    #endif
#elif SORA_FUNCTION_NUM_ARGS == 7
    #ifndef SORA_FUNCTION_7
        #define SORA_FUNCTION_7
        #include "SoraFunctionTemplate.h"
    #endif
#elif SORA_FUNCTION_NUM_ARGS == 8
    #ifndef SORA_FUNCTION_8
        #define SORA_FUNCTION_8
        #include "SoraFunctionTemplate.h"
    #endif
#elif SORA_FUNCTION_NUM_ARGS == 9
    #ifndef SORA_FUNCTION_9
        #define SORA_FUNCTION_9
        #include "SoraFunctionTemplate.h"
    #endif
#elif SORA_FUNCTION_NUM_ARGS == 10
    #ifndef SORA_FUNCTION_10
        #define SORA_FUNCTION_10
        #include "SoraFunctionTemplate.h"
    #endif
#elif SORA_FUNCTION_NUM_ARGS == 11
    #ifndef SORA_FUNCTION_11
        #define SORA_FUNCTION_11
        #include "SoraFunctionTemplate.h"
    #endif
#elif SORA_FUNCTION_NUM_ARGS == 12
    #ifndef SORA_FUNCTION_12
        #define SORA_FUNCTION_12
        #include "SoraFunctionTemplate.h"
    #endif
#endif
